# Generated by Django 4.2.1 on 2023-07-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_name_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='По умолчанию', max_length=512, verbose_name='Комментарий'),
        ),
    ]
