# Generated by Django 4.2.1 on 2023-07-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating_author',
            new_name='rating',
        ),
    ]
